services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports: 
      - 5432:5432 
  
  back:
    image: listaback
    ports:
    - 8000:8000

  front:
    image: frontlistatarefas
    ports:
    - 3000:3000
  
volumes:
  pgdata: